# Generated by Django 3.0.3 on 2020-02-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20200226_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='watch',
        ),
        migrations.AddField(
            model_name='topic',
            name='watch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
